name: flask pipeline

on:
   push:
      branches:
        - main

jobs:
    python_app:           
         runs-on: ubuntu-latest 

         steps:
            - uses: actions/checkout@v4

            - name: setting up python in your runner
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Installing dependencies  
              run: |
                 python -m pip install --upgrade pip
                 pip install -r requirements.txt

            - name: setting up test cases
              run : echo "testing is completed"   
